theme: jekyll-theme-architect
title: MacrAris Progetti Excel VBA Macro
description: Progetti di automazione realizzati con le Macro di Excel in ambito aziendale nelle funzioni di Gestione Crediti commerciali e Controllo di gestione.
show_downloads: true
Github:
    zip_url: www.macraris.it
