theme: jekyll-theme-architect
title: Macraris Progetti Excel VBA Automazione
description: Progetti di automazione realizzati con le Macro di Excel in ambito aziendale nelle funzioni di Gestione Crediti commerciali e Controllo di gestione.
show_downloads: true
github:
    aris_url: https://macraris.com/
    vba_url: https://macraris.com/vba-macro/
# Google Analytics
google_analytics: UA-112751924-2
